messages:
  not-player: "Only a player can execute this command"
  help: "&7Voucheros Help\n/voucheros create <name> - Creates a new Paper Item\n/voucheros give <name> [player] - Gives you or a player a paper item\n/voucheros setcommand <name> <command> - Sets the command which executes when clicked\n/voucheros setdisplayname <name> <displayname> - Sets the display name of the item\n/voucheros remove <name> - Removes the specified item\n/voucheros list - Lists all of the items"
  incorrect-params: "&cIncorrect Command Parameters"
  created: "&7Created {0} with a UUID of {1}"
  item-doesnt-exist: "&cThe voucher {0} doesn't exist!"
  target-doesnt-exist: "&cThe player {0} doesn't exist or is currently offline!"
  success-recieved: "&7You have been given {0}"
  success-given: "&7You have given {0} to {1}"
  item-deleted: "&7You have deleted the voucher {0}"
  command-set: "&7You have set the command &8''{0}'' &7for the item {1}"
  displayname-set: "&7You have set the displayname &8''{0}'' &7for the item {1}"
  already-exists: "&c{0} already exists!"
  error-occured: "&cAn error occured!"
  permission-denied: "&cYou do not have permission to execute this command"
  list-header: "&7ITEM NAME | DISPLAY NAME | COMMAND | UUID"
  list-format: "&7{0} &7| {1} &7| &7{2} &7| {3}"
  no-items: "&cThere are no items to list"
items:
